---
title: "Tutorial 4: Figures, Tables, and Cross-Referencing"
author: "Vikash Raam"
format: html
editor: visual
bibliography: references.bib

execute: 
  echo: true
  warning: false
  message: false
---

using the dataset @penguin_data

```{r}
#| label: fig-penguins-scatter
#| fig-cap: "Body mass vs. Flipper length for three penguin species."
#| warning: false
library(ggplot2)
library(palmerpenguins)

ggplot(penguins, aes(x = flipper_length_mm, y = body_mass_g, color = species)) +
  geom_point() +
  theme_minimal()
```

## Task 2 : creating professional tables

```{r}
#| label: tbl-penguin-summary
#| tbl-cap: "Mean body mass of penguins by species and sex."
library(dplyr)

penguins |>
  filter(!is.na(sex)) |>
  group_by(species, sex) |>
  summarise(mean_mass = mean(body_mass_g)) |>
  knitr::kable()
```

## **Task 3: Dynamic Cross-Referencing**

As shown in @fig-penguins-scatter , there is a clear positive correlation between flipper length and body mass. The specific averages for each group are detailed in @tbl-penguin-summary.
